services:
  postgres:
    image: postgres:14
    container_name: codeswap_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: codeswap
    ports:
      - "5543:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  logic:
    build:
      context: ./logic
    container_name: logic
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/codeswap?schema=public
    depends_on:
      - postgres
    command: ["npm", "run", "test"]

  back:
    build:
      context: .
      dockerfile: back/Dockerfile
    ports:
      - "3300:3300"
    depends_on:
      - postgres

  front:
    build:
      context: ./front
    container_name: front
    ports:
      - "5173:5173"
    depends_on:
      - back

volumes:
  postgres_data:
