name: Tests - Logic Only

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  logic-tests:
    name: Run tests in logic/
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: logic

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
